services:
  app:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Streamlit frontend
    env_file:
      - .env
    environment:
      - SERVER_URL=http://localhost:8000
      - IMAGE_INPUT_DIR=/app/uploads/Images
      - DB_PATH=/app/database/database.db
      - WANDB_API_KEY=${WANDB_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
      - wandb:/root/.wandb
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - autoaudit-network
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
        - action: sync+restart
          path: .
          target: /app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - autoaudit-network

volumes:
  redis_data:
  wandb:

networks:
  autoaudit-network:
    driver: bridge
