version: '3.9'

x-common-variables: &common-variables
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1
  REDIS_URL: redis://redis:6379/0
  
x-app-environment: &app-environment
  <<: *common-variables
  SERVER_URL: http://localhost:8000
  IMAGE_INPUT_DIR: /app/uploads/Images
  DB_PATH: /app/database/database.db
  WANDB_API_KEY: ${WANDB_API_KEY}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  WORKERS_COUNT: ${WORKERS_COUNT:-4}
  MAX_CONCURRENT_WORKFLOWS: ${MAX_CONCURRENT_WORKFLOWS:-10}

services:
  # Redis for caching and message queue
  redis:
    image: redis:7-alpine
    container_name: autoaudit_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autoaudit-network
    restart: unless-stopped

  # Main application with backend and frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
    image: autoaudit:latest
    container_name: autoaudit_app
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Streamlit frontend
    env_file:
      - .env
    environment:
      <<: *app-environment
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
      - ./logs:/app/logs
      - ./cache:/app/cache
      - wandb:/home/autoaudit/.wandb
      # Development volume mounts (comment out for production)
      - ./flow:/app/flow:ro
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - autoaudit-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  wandb:
    driver: local

networks:
  autoaudit-network:
    driver: bridge